# Generated by Django 5.2.7 on 2025-10-07 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_description_alter_event_all_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(
                check=models.Q(end__gte=models.F('start')),
                name='event_end_gte_start',
            ),
        ),
    ]
