# Generated by Django 5.2.7 on 2025-10-07 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_event_end_gte_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_user_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField()),
                ('sync_token', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('watch_channel_id', models.CharField(blank=True, max_length=255)),
                ('watch_resource_id', models.CharField(blank=True, max_length=255)),
                ('watch_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='google_etag',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='google_event_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='google_ical_uid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='google_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='google_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('local', 'Created in app'), ('google', 'Created in Google'), ('synced', 'Synced between app and Google')], default='local', max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['pilot', 'google_event_id'], name='api_event_pilot_i_0a8426_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['pilot', 'google_ical_uid'], name='api_event_pilot_i_08503b_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('google_event_id', ''), _negated=True), fields=('pilot', 'google_event_id'), name='unique_google_event_per_user'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('google_ical_uid', ''), _negated=True), fields=('pilot', 'google_ical_uid'), name='unique_google_ical_per_user'),
        ),
        migrations.AddField(
            model_name='googleaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='googleaccount',
            unique_together={('user', 'google_user_id')},
        ),
    ]
