# Generated by Django 5.2.7 on 2025-10-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_recurrence_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('local', 'Created in app'), ('google', 'Created in Google'), ('synced', 'Synced between app and Google'), ('brightspace', 'Imported from Brightspace')], default='local', max_length=20),
        ),
    ]
