# Generated by Django 5.2.7 on 2025-10-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_brightspacefeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brightspacefeed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
