# Generated by Django 5.2.7 on 2025-10-23 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('response_status', models.CharField(choices=[('needsAction', 'Needs action'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative')], default='needsAction', max_length=20)),
                ('optional', models.BooleanField(default=False)),
                ('is_organizer', models.BooleanField(default=False)),
                ('is_self', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='api.event')),
            ],
            options={
                'ordering': ['event_id', 'email'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
