# Generated by Django 5.2.8 on 2025-11-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_eventattendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
