# Generated by Django 5.2.8 on 2025-11-19 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_emoji_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='ParsedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('email_body', models.TextField()),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('parsed_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_from_email', to='api.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-parsed_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='api_parsede_user_id_40a561_idx'), models.Index(fields=['user', 'message_id'], name='api_parsede_user_id_9a5310_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'message_id'), name='unique_parsed_email_per_user')],
            },
        ),
    ]
